version: '3'
silent: true
tasks:
  default:
    cmds:
      - task -l

  update:
    cmds:
      - git rebase || true
      - git add -A . || true
      - git commit -m "update" || true
      - git push || true