name: Generate glyphs

on:
  push:
    paths:
      - 'src/**/*.ttf'
      - 'src/**/*.otf'
      - '.github/workflows/generate_glyphs.yaml'
      - 'generate_glyphs.js'
  workflow_dispatch:

jobs:
  build:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou la version que vous préférez

      - name: Install dependencies
        run: npm install

      - name: Generate glyph PBF
        run: npm run build

      - name: Commit glyphs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: regenerate glyphs"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}